// 1,Javascript is a client side scripting languge 

// matlb js apki client side scripting karni ka kaam ati hai

// js client side scripting aska kia matlb hai 

// matlb apka web page hai aska andr programmtically logic laga chtain hain to wo logic ap likh skte hain ex

// jo button hai apka os py agr click kro to form submit ho jai

// DOM , Document object model /dom matlb asa smjo ki ek page hota hai 

// it is used programmtically perfrom action within page



// WHAT YOU CAN DO WITH JAVA

// 1, Javascript can execute not only in the browser but also in the server




